### PR TITLE
Add colormap create tutorial

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Comment by lee1043** [comment]
@mattben Thanks for checking and merging this.

**Comment by doutriaux1** [comment]
@lee1043  I feel this should not be inside the VCS section. it is barely using any vcs features. The "Create colormap" in the vcs section should show how to create a colormap with vcs function (i.e x.createcolormap() and then cmap.setcolorcell(...)

I feel this is more of a matpltlib transplant/hack 

Don't get me wrong it is a very valuable notebook, but we should create a special section for these sort of things. Like a "Tips and Tricks" or something like that.

@lee1043 @williams13 what do you think?

**Comment by lee1043** [comment]
@doutriaux1 Your comment has a point. I agree that it is more of "hack". Maybe adding VCS function such as `x.createcolormap()` upfront of the notebook makes more sense. I will try that as well.

But meanwhile I was trying to be more on user's side of view. I am curious if user installs UV-CDAT via conda, do they get Matplotlib installed? (I believe so but please correct me if I am wrong). If so, using two lines of code, one from VCS and one other from Matplotlib, should not be a matter for users as long as it works in a simple way.

I am completely open to move this to "hack" menu. We however already have separated places for similar purpose I think; gallery and tutorial, I am not sure how adding one more place would work.

**Comment by doutriaux1** [comment]
@lee1043 yes uvcdat/vcs come with matplotlib under the hood as well. I think your idea of adding the *official* vcs way first and then move on to your user-defined function makes more sense.

**Pull request merged**
