### PR TITLE
Added boxfill ipython tutorial

### PR DESCRIPTION
**Pull request by chaosphere2112**

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@embrown To view the ipython notebook I told you about, you can go [here](https://github.com/chaosphere2112/uvcdat-site/blob/93a5649b0d64e8f324fc1289b218b6fa0e2a92a8/iPython/boxfill/boxfill.ipynb)

**Comment by chaosphere2112** [comment]
@mattben merge plz kthxbai

**Comment by doutriaux1** [comment]
@mattben I don't see it on the website with the other one. Where did it go?

**Comment by mattben** [comment]
@doutriaux1 looks like my cron job is not running correctly I'll fix it.
http://uvcdat.llnl.gov/tutorials.html is updated now

**Pull request merged**
