### PR TITLE
Added changelog for 2.4 and 2.2

### PR DESCRIPTION
**Pull request by chaosphere2112**
Adds the 2.4 and 2.2 changelog to the website

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chaosphere2112 do you want me to merge this? Or are you still working on it?

**Comment by chaosphere2112** [comment]
@doutriaux1 No, I was waiting till you weighed in with @aashish24 on the idea of writing up a document discussing all of the bugs we've fixed in this release.

**Comment by doutriaux1** [comment]
@chaosphere2112 isn't what [this](https://github.com/UV-CDAT/uvcdat/wiki/2.4RC3-Release-Notes) is supposed to be?

**Comment by aashish24** [comment]
thanks @chaosphere2112

**Pull request merged**
